defaults:
  atlas_width: 512
  atlas_height: 512
  padding: 1
  on_missing: skip
  clean_output: true
  starsector_xadvance_compat: true
  overrides:
    "{": { xadvance: 0, width: 0, height: 0 }
    "}": { xadvance: 0, width: 0, height: 0 }

outputs:
  - name: insignia15LTaa
    # dir: lantinghei
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/insignia15LTaa.fnt
        y_adjust: +1
        extra_line_height: +1
      - type: ttf
        path: "source/方正兰亭中粗黑.ttf"
        size: 15
        color: [255, 255, 255]
        y_adjust: 0
        xadvance_adjust: 0
        extra_line_height: +2
        supersample: 8
        hinting: light
    chars:
      - { file: charset/chars.txt }

  - name: insignia21LTaa
    # dir: lantinghei
    atlas_width: 2048
    atlas_height: -1
    size: 18 # 覆写为18来避免在游戏中实际使用时被二次缩放，导致字形模糊
    sources:
      - type: fnt
        path: source/insignia17LTaa.fnt
        extra_line_height: +1
      - type: ttf
        path: "source/方正兰亭中粗黑.ttf"
        size: 16
        color: [255, 255, 255]
        y_adjust: 0
        xadvance_adjust: +1
        extra_line_height: +2
        supersample: 4
        hinting: light
    chars:
      - { file: charset/chars.txt }

  - name: insignia25LTaa
    # dir: lantinghei
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/insignia25LTaa.fnt
        y_adjust: +1
        extra_line_height: +1
      - type: ttf
        path: "source/方正兰亭中粗黑.ttf"
        size: 22
        color: [255, 255, 255]
        y_adjust: 0
        xadvance_adjust: +1
        extra_line_height: +2
        supersample: 4
        hinting: light
    chars:
      - { file: charset/chars.txt }

  # - name: insignia15LTaa
  #   dir: lxgw
  #   atlas_width: -1
  #   atlas_height: -1
  #   sources:
  #     - type: fnt
  #       path: source/insignia15LTaa.fnt
  #       extra_line_height: +1
  #     - type: ttf
  #       path: source/LXGWNeoXiHeiPlus.ttf
  #       size: 15
  #       color: [255, 255, 255]
  #       y_adjust: 0
  #       xadvance_adjust: 0
  #       extra_line_height: +1
  #       supersample: 8
  #       hinting: light
  #       bold: 0.2
  #   chars:
  #     - { file: charset/chars.txt }

  # - name: insignia21LTaa
  #   dir: lxgw
  #   atlas_width: -1
  #   atlas_height: -1
  #   sources:
  #     - type: fnt
  #       path: source/insignia21LTaa.fnt
  #       extra_line_height: +2
  #     - type: ttf
  #       path: source/LXGWNeoXiHeiPlus.ttf
  #       size: 21
  #       color: [255, 255, 255]
  #       y_adjust: 0
  #       xadvance_adjust: 0
  #       extra_line_height: +2
  #       supersample: 4
  #       hinting: light
  #       bold: 0.25
  #   chars:
  #     - { file: charset/chars.txt }

  # - name: insignia25LTaa
  #   dir: lxgw
  #   atlas_width: -1
  #   atlas_height: -1
  #   sources:
  #     - type: fnt
  #       path: source/insignia25LTaa.fnt
  #       extra_line_height: +3
  #     - type: ttf
  #       path: source/LXGWNeoXiHeiPlus.ttf
  #       size: 25
  #       color: [255, 255, 255]
  #       y_adjust: 0
  #       xadvance_adjust: 0
  #       extra_line_height: +3
  #       supersample: 4
  #       hinting: light
  #       bold: 0.35
  #   chars:
  #     - { file: charset/chars.txt }

  - name: orbitron12condensed
    # dir: ruizi
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/orbitron12condensed.fnt
      - type: ttf
        path: source/锐字逼格青春粗黑体简2.0.ttf
        size: 16
        color: [255, 255, 255]
        y_adjust: -1
        supersample: 8
        hinting: light
        bold: 0.1
    chars:
      - { file: charset/chars.txt }

  - name: orbitron20aa
    # dir: ruizi
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/orbitron20aa.fnt
      - type: ttf
        path: source/锐字逼格青春粗黑体简2.0.ttf
        size: 18
        color: [255, 255, 255]
        y_adjust: 1
        supersample: 4
        hinting: light
    chars:
      - { file: charset/chars.txt }

  - name: orbitron20aabold
    # dir: ruizi
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/orbitron20aabold.fnt
      - type: ttf
        path: source/锐字逼格青春粗黑体简2.0.ttf
        size: 18
        color: [255, 255, 255]
        y_adjust: 1
        supersample: 4
        hinting: light
        bold: 0.2
    chars:
      - { file: charset/chars.txt }

  - name: orbitron24aa
    # dir: ruizi
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/orbitron24aa.fnt
      - type: ttf
        path: source/锐字逼格青春粗黑体简2.0.ttf
        size: 20
        color: [255, 255, 255]
        y_adjust: 1
        supersample: 4
        hinting: light
    chars:
      - { file: charset/chars.txt }

  - name: orbitron24aabold
    # dir: ruizi
    atlas_width: 2048
    atlas_height: -1
    sources:
      - type: fnt
        path: source/orbitron24aabold.fnt
      - type: ttf
        path: source/锐字逼格青春粗黑体简2.0.ttf
        size: 20
        color: [255, 255, 255]
        y_adjust: 1
        supersample: 4
        hinting: light
        bold: 0.2
    chars:
      - { file: charset/chars.txt }
